### PR TITLE
implement verbosity

### PR DESCRIPTION
**Pull request by resmo**

### CODE REVIEW

**Comment by gaudenz** [comment]
This feature looks nice. No comments on the code itself. I have just one suggestion. I would call the command line parameter `--debug` and the environment variable `CLOUDSCALE_DEBUG` instead. The output this produces looks more like debugging output. As a user I would expect a `--verbose` option to output more information about the objects (eg. more detailed server list), not more information about the API requests done. Also with the Python logging formatting this looks more like debugging output.

Something a bit different not really specific to this PR: Is there a way to make certain CLI flags "global" so you don't have to define them for every command? Currently there is a lot of code duplication for all the flags that are the same for each command.

**Review by gaudenz — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by resmo** [comment]
> This feature looks nice. No comments on the code itself. I have just one suggestion. I would call the command line parameter `--debug` and the environment variable `CLOUDSCALE_DEBUG` instead. The output this produces looks more like debugging output. As a user I would expect a `--verbose` option to output more information about the objects (eg. more detailed server list), not more information about the API requests done. Also with the Python logging formatting this looks more like debugging output.

--debug would be indeed a appropriate option name.

> 
> Something a bit different not really specific to this PR: Is there a way to make certain CLI flags "global" so you don't have to define them for every command? Currently there is a lot of code duplication for all the flags that are the same for each command.

Currently the only reason against  "globaly" options is the `cloudscale-cli version` case, which takes no optioins at all. But at the end to have a non-functional options for `cloudscale-cli version` would not a big issue IMHO.

**Comment by gaudenz** [comment]
I would live with the non functional options on the version command (or make that an option itself `--version`) and make the common options global. But I leave this up to you and this is certainly nothing for this PR.

**Comment by resmo** [comment]
needs rebase and I would like to merge #4 first and working on top

**Pull request merged**
